//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 12:20:26 PM EDT 
//


package com.td.mbna.msec.midtier.disclosure.xsd.metadata.ip;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Variant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Party">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PartyTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Agreement">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AgreementTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GroupingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MinPayOptionSetID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PromotionOffer">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PromotionTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AdjudicationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AnnualInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="PromotionFeatureAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="PromotionFeatureStartDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="PromotionFeatureAnnualInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="PromotionFeatureDurationNum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="PromotionFeatureDurationTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PromotionFeatureEarlyExpiryDt" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="PromotionFeatureEndDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="PromotionOfferId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PercentageFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="FixedAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="MinimumAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="MaximumAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="PurchaseAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="NickName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TotalEstimatedInterestAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="TotalPaymentPlanAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="CostofBorrowingAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="MonthlyPaymentAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentTypeCd",
    "variant",
    "party"
})
@XmlRootElement(name = "DocumentRq")
public class DocumentRq {

    @XmlElement(name = "DocumentTypeCd", required = true)
    protected String documentTypeCd;
    @XmlElement(name = "Variant", required = true)
    protected String variant;
    @XmlElement(name = "Party", required = true)
    protected Party party;

    /**
     * Gets the value of the documentTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentTypeCd() {
        return documentTypeCd;
    }

    /**
     * Sets the value of the documentTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentTypeCd(String value) {
        this.documentTypeCd = value;
    }

    /**
     * Gets the value of the variant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariant() {
        return variant;
    }

    /**
     * Sets the value of the variant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariant(String value) {
        this.variant = value;
    }

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link Party }
     *     
     */
    public Party getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link Party }
     *     
     */
    public void setParty(Party value) {
        this.party = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PartyTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Agreement">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AgreementTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GroupingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MinPayOptionSetID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PromotionOffer">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PromotionTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AdjudicationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnnualInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="PromotionFeatureAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="PromotionFeatureStartDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="PromotionFeatureAnnualInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="PromotionFeatureDurationNum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="PromotionFeatureDurationTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PromotionFeatureEarlyExpiryDt" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="PromotionFeatureEndDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="PromotionOfferId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PercentageFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="FixedAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="MinimumAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="MaximumAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="PurchaseAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="NickName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TotalEstimatedInterestAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="TotalPaymentPlanAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="CostofBorrowingAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="MonthlyPaymentAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partyTypeCd",
        "agreement",
        "promotionOffer"
    })
    public static class Party {

        @XmlElement(name = "PartyTypeCd", required = true)
        protected String partyTypeCd;
        @XmlElement(name = "Agreement", required = true)
        protected Agreement agreement;
        @XmlElement(name = "PromotionOffer", required = true)
        protected PromotionOffer promotionOffer;

        /**
         * Gets the value of the partyTypeCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartyTypeCd() {
            return partyTypeCd;
        }

        /**
         * Sets the value of the partyTypeCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartyTypeCd(String value) {
            this.partyTypeCd = value;
        }

        /**
         * Gets the value of the agreement property.
         * 
         * @return
         *     possible object is
         *     {@link Agreement }
         *     
         */
        public Agreement getAgreement() {
            return agreement;
        }

        /**
         * Sets the value of the agreement property.
         * 
         * @param value
         *     allowed object is
         *     {@link Agreement }
         *     
         */
        public void setAgreement(Agreement value) {
            this.agreement = value;
        }

        /**
         * Gets the value of the promotionOffer property.
         * 
         * @return
         *     possible object is
         *     {@link PromotionOffer }
         *     
         */
        public PromotionOffer getPromotionOffer() {
            return promotionOffer;
        }

        /**
         * Sets the value of the promotionOffer property.
         * 
         * @param value
         *     allowed object is
         *     {@link PromotionOffer }
         *     
         */
        public void setPromotionOffer(PromotionOffer value) {
            this.promotionOffer = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AgreementTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GroupingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MinPayOptionSetID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "agreementTypeCd",
            "groupingCode",
            "minPayOptionSetID"
        })
        public static class Agreement {

            @XmlElement(name = "AgreementTypeCd", required = true)
            protected String agreementTypeCd;
            @XmlElement(name = "GroupingCode", required = true)
            protected String groupingCode;
            @XmlElement(name = "MinPayOptionSetID", required = true)
            protected String minPayOptionSetID;

            /**
             * Gets the value of the agreementTypeCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAgreementTypeCd() {
                return agreementTypeCd;
            }

            /**
             * Sets the value of the agreementTypeCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAgreementTypeCd(String value) {
                this.agreementTypeCd = value;
            }

            /**
             * Gets the value of the groupingCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGroupingCode() {
                return groupingCode;
            }

            /**
             * Sets the value of the groupingCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGroupingCode(String value) {
                this.groupingCode = value;
            }

            /**
             * Gets the value of the minPayOptionSetID property.
             * 
             */
            public String getMinPayOptionSetID() {
                return minPayOptionSetID;
            }

            /**
             * Sets the value of the minPayOptionSetID property.
             * 
             */
            public void setMinPayOptionSetID(String value) {
                this.minPayOptionSetID = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PromotionTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AdjudicationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AnnualInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="PromotionFeatureAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="PromotionFeatureStartDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="PromotionFeatureAnnualInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="PromotionFeatureDurationNum" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="PromotionFeatureDurationTypeCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PromotionFeatureEarlyExpiryDt" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="PromotionFeatureEndDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="PromotionOfferId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PercentageFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="FixedAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="MinimumAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="MaximumAmtFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="PurchaseAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="NickName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TotalEstimatedInterestAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="TotalPaymentPlanAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="CostofBorrowingAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="MonthlyPaymentAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "promotionTypeCd",
            "adjudicationMethod",
            "annualInterestRate",
            "promotionFeatureAmt",
            "promotionFeatureStartDt",
            "promotionFeatureAnnualInterestRate",
            "promotionFeatureDurationNum",
            "promotionFeatureDurationTypeCd",
            "promotionFeatureEarlyExpiryDt",
            "promotionFeatureEndDt",
            "promotionOfferId",
            "percentageFee",
            "fixedAmtFee",
            "minimumAmtFee",
            "maximumAmtFee",
            "purchaseAmt",
            "nickName",
            "totalEstimatedInterestAmt",
            "totalPaymentPlanAmt",
            "costofBorrowingAmt",
            "monthlyPaymentAmt"
        })
        public static class PromotionOffer {

            @XmlElement(name = "PromotionTypeCd", required = true)
            protected String promotionTypeCd;
            @XmlElement(name = "AdjudicationMethod", required = true)
            protected String adjudicationMethod;
            @XmlElement(name = "AnnualInterestRate", required = true)
            protected BigDecimal annualInterestRate;
            @XmlElement(name = "PromotionFeatureAmt", required = true)
            protected BigDecimal promotionFeatureAmt;
            @XmlElement(name = "PromotionFeatureStartDt", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar promotionFeatureStartDt;
            @XmlElement(name = "PromotionFeatureAnnualInterestRate", required = true)
            protected BigDecimal promotionFeatureAnnualInterestRate;
            @XmlElement(name = "PromotionFeatureDurationNum")
            @XmlSchemaType(name = "unsignedByte")
            protected short promotionFeatureDurationNum;
            @XmlElement(name = "PromotionFeatureDurationTypeCd", required = true)
            protected String promotionFeatureDurationTypeCd;
            @XmlElement(name = "PromotionFeatureEarlyExpiryDt", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar promotionFeatureEarlyExpiryDt;
            @XmlElement(name = "PromotionFeatureEndDt", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar promotionFeatureEndDt;
            @XmlElement(name = "PromotionOfferId", required = true)
            protected String promotionOfferId;
            @XmlElement(name = "PercentageFee", required = true)
            protected BigDecimal percentageFee;
            @XmlElement(name = "FixedAmtFee", required = true)
            protected BigDecimal fixedAmtFee;
            @XmlElement(name = "MinimumAmtFee", required = true)
            protected BigDecimal minimumAmtFee;
            @XmlElement(name = "MaximumAmtFee", required = true)
            protected BigDecimal maximumAmtFee;
            @XmlElement(name = "PurchaseAmt", required = true)
            protected BigDecimal purchaseAmt;
            @XmlElement(name = "NickName", required = true)
            protected String nickName;
            @XmlElement(name = "TotalEstimatedInterestAmt", required = true)
            protected BigDecimal totalEstimatedInterestAmt;
            @XmlElement(name = "TotalPaymentPlanAmt", required = true)
            protected BigDecimal totalPaymentPlanAmt;
            @XmlElement(name = "CostofBorrowingAmt", required = true)
            protected BigDecimal costofBorrowingAmt;
            @XmlElement(name = "MonthlyPaymentAmt", required = true)
            protected BigDecimal monthlyPaymentAmt;

            /**
             * Gets the value of the promotionTypeCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPromotionTypeCd() {
                return promotionTypeCd;
            }

            /**
             * Sets the value of the promotionTypeCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPromotionTypeCd(String value) {
                this.promotionTypeCd = value;
            }

            /**
             * Gets the value of the adjudicationMethod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdjudicationMethod() {
                return adjudicationMethod;
            }

            /**
             * Sets the value of the adjudicationMethod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdjudicationMethod(String value) {
                this.adjudicationMethod = value;
            }

            /**
             * Gets the value of the annualInterestRate property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAnnualInterestRate() {
                return annualInterestRate;
            }

            /**
             * Sets the value of the annualInterestRate property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAnnualInterestRate(BigDecimal value) {
                this.annualInterestRate = value;
            }

            /**
             * Gets the value of the promotionFeatureAmt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPromotionFeatureAmt() {
                return promotionFeatureAmt;
            }

            /**
             * Sets the value of the promotionFeatureAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPromotionFeatureAmt(BigDecimal value) {
                this.promotionFeatureAmt = value;
            }

            /**
             * Gets the value of the promotionFeatureStartDt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPromotionFeatureStartDt() {
                return promotionFeatureStartDt;
            }

            /**
             * Sets the value of the promotionFeatureStartDt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPromotionFeatureStartDt(XMLGregorianCalendar value) {
                this.promotionFeatureStartDt = value;
            }

            /**
             * Gets the value of the promotionFeatureAnnualInterestRate property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPromotionFeatureAnnualInterestRate() {
                return promotionFeatureAnnualInterestRate;
            }

            /**
             * Sets the value of the promotionFeatureAnnualInterestRate property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPromotionFeatureAnnualInterestRate(BigDecimal value) {
                this.promotionFeatureAnnualInterestRate = value;
            }

            /**
             * Gets the value of the promotionFeatureDurationNum property.
             * 
             */
            public short getPromotionFeatureDurationNum() {
                return promotionFeatureDurationNum;
            }

            /**
             * Sets the value of the promotionFeatureDurationNum property.
             * 
             */
            public void setPromotionFeatureDurationNum(short value) {
                this.promotionFeatureDurationNum = value;
            }

            /**
             * Gets the value of the promotionFeatureDurationTypeCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPromotionFeatureDurationTypeCd() {
                return promotionFeatureDurationTypeCd;
            }

            /**
             * Sets the value of the promotionFeatureDurationTypeCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPromotionFeatureDurationTypeCd(String value) {
                this.promotionFeatureDurationTypeCd = value;
            }

            /**
             * Gets the value of the promotionFeatureEarlyExpiryDt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPromotionFeatureEarlyExpiryDt() {
                return promotionFeatureEarlyExpiryDt;
            }

            /**
             * Sets the value of the promotionFeatureEarlyExpiryDt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPromotionFeatureEarlyExpiryDt(XMLGregorianCalendar value) {
                this.promotionFeatureEarlyExpiryDt = value;
            }

            /**
             * Gets the value of the promotionFeatureEndDt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPromotionFeatureEndDt() {
                return promotionFeatureEndDt;
            }

            /**
             * Sets the value of the promotionFeatureEndDt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPromotionFeatureEndDt(XMLGregorianCalendar value) {
                this.promotionFeatureEndDt = value;
            }

            /**
             * Gets the value of the promotionOfferId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPromotionOfferId() {
                return promotionOfferId;
            }

            /**
             * Sets the value of the promotionOfferId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPromotionOfferId(String value) {
                this.promotionOfferId = value;
            }

            /**
             * Gets the value of the percentageFee property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPercentageFee() {
                return percentageFee;
            }

            /**
             * Sets the value of the percentageFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPercentageFee(BigDecimal value) {
                this.percentageFee = value;
            }

            /**
             * Gets the value of the fixedAmtFee property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getFixedAmtFee() {
                return fixedAmtFee;
            }

            /**
             * Sets the value of the fixedAmtFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setFixedAmtFee(BigDecimal value) {
                this.fixedAmtFee = value;
            }

            /**
             * Gets the value of the minimumAmtFee property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMinimumAmtFee() {
                return minimumAmtFee;
            }

            /**
             * Sets the value of the minimumAmtFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMinimumAmtFee(BigDecimal value) {
                this.minimumAmtFee = value;
            }

            /**
             * Gets the value of the maximumAmtFee property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMaximumAmtFee() {
                return maximumAmtFee;
            }

            /**
             * Sets the value of the maximumAmtFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMaximumAmtFee(BigDecimal value) {
                this.maximumAmtFee = value;
            }

            /**
             * Gets the value of the purchaseAmt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPurchaseAmt() {
                return purchaseAmt;
            }

            /**
             * Sets the value of the purchaseAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPurchaseAmt(BigDecimal value) {
                this.purchaseAmt = value;
            }

            /**
             * Gets the value of the nickName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNickName() {
                return nickName;
            }

            /**
             * Sets the value of the nickName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNickName(String value) {
                this.nickName = value;
            }

            /**
             * Gets the value of the totalEstimatedInterestAmt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotalEstimatedInterestAmt() {
                return totalEstimatedInterestAmt;
            }

            /**
             * Sets the value of the totalEstimatedInterestAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotalEstimatedInterestAmt(BigDecimal value) {
                this.totalEstimatedInterestAmt = value;
            }

            /**
             * Gets the value of the totalPaymentPlanAmt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotalPaymentPlanAmt() {
                return totalPaymentPlanAmt;
            }

            /**
             * Sets the value of the totalPaymentPlanAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotalPaymentPlanAmt(BigDecimal value) {
                this.totalPaymentPlanAmt = value;
            }

            /**
             * Gets the value of the costofBorrowingAmt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getCostofBorrowingAmt() {
                return costofBorrowingAmt;
            }

            /**
             * Sets the value of the costofBorrowingAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setCostofBorrowingAmt(BigDecimal value) {
                this.costofBorrowingAmt = value;
            }

            /**
             * Gets the value of the monthlyPaymentAmt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMonthlyPaymentAmt() {
                return monthlyPaymentAmt;
            }

            /**
             * Sets the value of the monthlyPaymentAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMonthlyPaymentAmt(BigDecimal value) {
                this.monthlyPaymentAmt = value;
            }

        }

    }

}
