//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 12:20:26 PM EDT 
//


package com.td.mbna.msec.midtier.disclosure.xsd.metadata.ip;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.td.schemas.tdct.srm.disclosuresandlettersapplication.disclosure.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.td.schemas.tdct.srm.disclosuresandlettersapplication.disclosure.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentRq }
     * 
     */
    public DocumentRq createDocumentRq() {
        return new DocumentRq();
    }

    /**
     * Create an instance of {@link DocumentRq.Party }
     * 
     */
    public DocumentRq.Party createDocumentRqParty() {
        return new DocumentRq.Party();
    }

    /**
     * Create an instance of {@link DocumentRq.Party.Agreement }
     * 
     */
    public DocumentRq.Party.Agreement createDocumentRqPartyAgreement() {
        return new DocumentRq.Party.Agreement();
    }

    /**
     * Create an instance of {@link DocumentRq.Party.PromotionOffer }
     * 
     */
    public DocumentRq.Party.PromotionOffer createDocumentRqPartyPromotionOffer() {
        return new DocumentRq.Party.PromotionOffer();
    }

}
