//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 12:20:26 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.td.com/tdct/srm/disclosuresandlettersapplication/disclosure/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.td.mbna.msec.midtier.disclosure.xsd.metadata.ip;
