package com.td.mbna.msec.midtier.framework;

/**
 * This interface contains framework constants.
 *
 */
public interface FrameworkConstants {
	// default bean name
	public static final String DefaultBeanName = "_DefaultBeanName_";
	// suffix of class generated by Shadowfax
	public static final String GeneratedImplClassSuffix = "OperationImpl";
	public static final String GeneratedClassSuffix = "Operation";
	// suffix of real implementation class
	public static final String RealImplClassSuffix = "OperationRealImpl";
	// suffix of stub implementation class
	public static final String StubImplClassSuffix = "OperationStubImpl";

}