package com.td.mbna.msec.midtier.transfer;

import com.td.mbna.msec.midtier.transfer.payload.addbalancetransfertocreditorpayee.AddBalanceTransferToCreditorPayeeRequest;
import com.td.mbna.msec.midtier.transfer.payload.addbalancetransfertocreditorpayee.AddBalanceTransferToCreditorPayeeResponse;
import com.td.mbna.msec.midtier.transfer.payload.adddeposittochequingpayee.AddDepositToChequingPayeeRequest;
import com.td.mbna.msec.midtier.transfer.payload.adddeposittochequingpayee.AddDepositToChequingPayeeResponse;
import com.td.mbna.msec.midtier.transfer.payload.balancetransfertocreditor.BalanceTransferToCreditorRequest;
import com.td.mbna.msec.midtier.transfer.payload.balancetransfertocreditor.BalanceTransferToCreditorResponse;
import com.td.mbna.msec.midtier.transfer.payload.deletebalancetransfertocreditorpayee.DeleteBalanceTransferToCreditorPayeeRequest;
import com.td.mbna.msec.midtier.transfer.payload.deletebalancetransfertocreditorpayee.DeleteBalanceTransferToCreditorPayeeResponse;
import com.td.mbna.msec.midtier.transfer.payload.deletedeposittochequingpayee.DeleteDepositToChequingPayeeRequest;
import com.td.mbna.msec.midtier.transfer.payload.deletedeposittochequingpayee.DeleteDepositToChequingPayeeResponse;
import com.td.mbna.msec.midtier.transfer.payload.deposittochequing.DepositToChequingRequest;
import com.td.mbna.msec.midtier.transfer.payload.deposittochequing.DepositToChequingResponse;
import com.td.mbna.msec.midtier.transfer.payload.getbalancetransfertocreditorpayees.GetBalanceTransferToCreditorPayeesRequest;
import com.td.mbna.msec.midtier.transfer.payload.getbalancetransfertocreditorpayees.GetBalanceTransferToCreditorPayeesResponse;
import com.td.mbna.msec.midtier.transfer.payload.getbalancetransfertocreditorsummary.GetBalanceTransferToCreditorSummaryRequest;
import com.td.mbna.msec.midtier.transfer.payload.getbalancetransfertocreditorsummary.GetBalanceTransferToCreditorSummaryResponse;
import com.td.mbna.msec.midtier.transfer.payload.getdeposittochequingpayees.GetDepositToChequingPayeesRequest;
import com.td.mbna.msec.midtier.transfer.payload.getdeposittochequingpayees.GetDepositToChequingPayeesResponse;
import com.td.mbna.msec.midtier.transfer.payload.getknowncardissuers.GetKnownCardIssuersRequest;
import com.td.mbna.msec.midtier.transfer.payload.getknowncardissuers.GetKnownCardIssuersResponse;
import com.td.mbna.msec.midtier.transfer.payload.updatebalancetransfertocreditorpayee.UpdateBalanceTransferToCreditorPayeeRequest;
import com.td.mbna.msec.midtier.transfer.payload.updatebalancetransfertocreditorpayee.UpdateBalanceTransferToCreditorPayeeResponse;
import com.td.mbna.msec.midtier.transfer.payload.updatedeposittochequingpayee.UpdateDepositToChequingPayeeRequest;
import com.td.mbna.msec.midtier.transfer.payload.updatedeposittochequingpayee.UpdateDepositToChequingPayeeResponse;

public interface TransferService {
	public BalanceTransferToCreditorResponse balanceTransferToCreditor(BalanceTransferToCreditorRequest balanceTransferToCreditorRequest, String... token);
	public GetBalanceTransferToCreditorPayeesResponse getBalanceTransferToCreditorPayees(GetBalanceTransferToCreditorPayeesRequest getBalanceTransferToCreditorPayeesRequest);
	public AddBalanceTransferToCreditorPayeeResponse addBalanceTransferToCreditorPayee(AddBalanceTransferToCreditorPayeeRequest addBalanceTransferToCreditorPayeeRequest);
	public DeleteBalanceTransferToCreditorPayeeResponse deleteBalanceTransferToCreditorPayee(DeleteBalanceTransferToCreditorPayeeRequest deleteBalanceTransferToCreditorPayeeRequest);
	public UpdateBalanceTransferToCreditorPayeeResponse updateBalanceTransferToCreditorPayee(UpdateBalanceTransferToCreditorPayeeRequest updateBalanceTransferToCreditorPayeeRequest);
	public DepositToChequingResponse depositToChequing(DepositToChequingRequest depositToChequingRequest, String... token);
	public GetDepositToChequingPayeesResponse getDepositToChequingPayees(GetDepositToChequingPayeesRequest getDepositToChequingPayeesRequest);
	public AddDepositToChequingPayeeResponse addDepositToChequingPayee(AddDepositToChequingPayeeRequest addDepositToChequingPayeeRequest);
	public DeleteDepositToChequingPayeeResponse deleteDepositToChequingPayee(DeleteDepositToChequingPayeeRequest deleteDepositToChequingPayeeRequest);
	public UpdateDepositToChequingPayeeResponse updateDepositToChequingPayee(UpdateDepositToChequingPayeeRequest updateDepositToChequingPayeeRequest, String... token);
	public GetKnownCardIssuersResponse getKnownCardIssuers(GetKnownCardIssuersRequest getKnownCardIssuersRequest);
	public GetBalanceTransferToCreditorSummaryResponse getBalanceTransferToCreditorSummary(GetBalanceTransferToCreditorSummaryRequest getBalanceTransferToCreditorSummaryRequest);
	
}
